name: clean_swiper
description: Clean Swiper is a starting point for clean and simple swiper. 
version: 0.0.3
author: Roman Nowicki <peengle@gmail.com>
homepage: https://github.com/clean/clean_swiper
repository: https://github.com/clean/clean_swiper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter